[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildPath = "."

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/healthz"
healthcheckTimeout = 100

# Ne PAS définir startCommand ici - laisser le Dockerfile utiliser start.sh
